version: '3.8'

services:
  binnav:
    build: .
    container_name: binnav
    ports:
      - "5173:5173"
    environment:
      - ADMIN_PASSWORD=AAssdd123
    volumes:
      - ./src/websiteData.js:/app/src/websiteData.js
      - ./public/assets:/app/public/assets
      - ./public/logos:/app/public/logos
    restart: unless-stopped
